version: '3'
services:
  validator:
    image: llm-defender-subnet
    build:
      context: .
      dockerfile: Dockerfile   
    command: /bin/bash -c "source /tmp/.venv/bin/activate && pip install -e /var/run/llm-defender-subnet && pip uninstall -y uvloop && python3 /var/run/llm-defender-subnet/llm_defender/neurons/validator.py --netuid ${NETUID} --subtensor.network ${SUBTENSOR_NETWORK} --wallet.path ${WALLET_PATH} --wallet.name ${VALIDATOR_WALLET} --wallet.hotkey ${VALIDATOR_HOTKEY} --logging.debug"
    volumes:
      - .:/var/run/llm-defender-subnet
    networks:
      llm-defender-subnet-network-development:
        ipv4_address: ${VALIDATOR_IP}

  miner:
    image: llm-defender-subnet
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/run/llm-defender-subnet
    command: /bin/bash -c "source /tmp/.venv/bin/activate && pip install -e /var/run/llm-defender-subnet && pip uninstall -y uvloop && python3 /var/run/llm-defender-subnet/llm_defender/neurons/miner.py --netuid ${NETUID} --subtensor.network ${SUBTENSOR_NETWORK} --wallet.path ${WALLET_PATH} --wallet.name ${MINER_WALLET} --wallet.hotkey ${MINER_HOTKEY} --logging.debug --axon.port ${MINER_PORT} --validator_min_stake 0 --axon.external_ip ${MINER_IP}"
    networks:
      llm-defender-subnet-network-development:
        ipv4_address: ${MINER_IP}

networks:
  llm-defender-subnet-network-development:
    driver: bridge
    ipam:
     config:
       - subnet: ${DOCKER_NETWORK_SUBNET}
         gateway: ${DOCKER_NETWORK_GATEWAY}